"""OpenCode platform adapter."""

from __future__ import annotations

import logging
from typing import ClassVar

from boff.adapters.base import PlatformAdapter, frontmatter_block, renders
from boff.artifacts import (
    Agent,
    EventHook,
    EventHooks,
    NativeHook,
    OutputStyle,
    PermissionRule,
    Permissions,
    Rule,
)
from boff.jsonutil import dumps_json
from boff.platform_layout import (
    OPENCODE_LAYOUT,
    PlatformLayout,
    opencode_instructions_glob_op,
    require_workspace_root,
)
from boff.types import FileOperation, MergeStrategy, Operation, Scope

_OC_TOOL = {
    "bash": "bash",
    "read": "read",
    "edit": "edit",
    "write": "edit",
    "glob": "glob",
    "grep": "grep",
    "agent": "task",
    "webfetch": "webfetch",
    "websearch": "websearch",
    "lsp": "lsp",
    "skill": "skill",
    "question": "question",
    "external_directory": "external_directory",
    "doom_loop": "doom_loop",
}

_ACTION_ORDER = {"allow": 0, "ask": 1, "deny": 2}

_log = logging.getLogger(__name__)


def _tool_condition(tools: tuple[str, ...]) -> str:
    """Render a JS boolean matching ``input.tool`` against the mapped tool names."""
    return " || ".join(f'input.tool === "{tool}"' for tool in tools)


def _native(hook: EventHook) -> NativeHook:
    """Return the hook's OpenCode binding; every normalized event maps on OpenCode."""
    native = hook.native_for("opencode")
    if native is None:  # pragma: no cover - defensive: EVENT_MAP covers opencode for all events
        raise ValueError(f"event '{hook.event}' has no opencode mapping")
    return native


def _opencode_plugin(hooks: tuple[EventHook, ...]) -> str:
    """Generate the auto-loaded OpenCode plugin that runs each hook with the BOFF_* contract."""
    after = [h for h in hooks if _native(h).event == "tool.execute.after"]
    # Every other OpenCode event (session.idle, session.start, session.deleted, ...) is a
    # plain side-effect handler with no tool payload. Group by event, preserving first-seen order.
    plain: dict[str, list[EventHook]] = {}
    for hook in hooks:
        oc_event = _native(hook).event
        if oc_event == "tool.execute.after":
            continue
        plain.setdefault(oc_event, []).append(hook)

    handlers: list[str] = []
    if after:
        lines = [
            "    'tool.execute.after': async (input, output) => {",
            "      const file = (output && output.args && output.args.filePath) || '';",
            "      const command = (output && output.args && output.args.command) || '';",
        ]
        for hook in after:
            is_bash = hook.event == "after_bash"
            tool = '"bash"' if is_bash else "input.tool"
            file_val = "''" if is_bash else "file"
            command_val = "command" if is_bash else "''"
            env = (
                f'{{ BOFF_EVENT: "{hook.event}", BOFF_TOOL: {tool}, '
                f"BOFF_FILE: {file_val}, BOFF_COMMAND: {command_val} }}"
            )
            cond = _tool_condition(_native(hook).tools)
            lines.append(f'      if ({cond}) {{ await run("{hook.name}", {env}); }}')
        lines.append("    },")
        handlers.append("\n".join(lines))
    for oc_event, event_hooks in plain.items():
        lines = [f"    '{oc_event}': async () => {{"]
        for hook in event_hooks:
            env = (
                f'{{ BOFF_EVENT: "{hook.event}", BOFF_TOOL: "", BOFF_FILE: "", BOFF_COMMAND: "" }}'
            )
            lines.append(f'      await run("{hook.name}", {env});')
        lines.append("    },")
        handlers.append("\n".join(lines))

    body = "\n".join(handlers)
    return (
        "// Generated by bun-off. Do not edit.\n"
        "export const boffHooks = async ({ $, directory }) => {\n"
        "  const run = async (name, env) => {\n"
        "    try {\n"
        '      await $`sh ${directory + "/.opencode/hooks/" + name}`'
        ".env({ ...process.env, ...env });\n"
        "    } catch (_) {}\n"
        "  };\n"
        "  return {\n"
        f"{body}\n"
        "  };\n"
        "};\n"
    )


def _opencode_permission_block(rules: tuple[PermissionRule, ...]) -> dict[str, object]:
    """Group rules by OpenCode tool key, ordering each tool's patterns allow < ask < deny.

    Ordering allow < ask < deny means that, under OpenCode's last-match-wins rule, the
    highest-precedence verdict wins (matching Claude's deny > ask > allow tier priority).
    """
    by_tool: dict[str, list[PermissionRule]] = {}
    for rule in rules:
        key = _OC_TOOL.get(rule.tool)
        if key is None:
            raise ValueError(
                f"permission tool '{rule.tool}' is not supported on opencode; "
                "scope it with available_on: [claude]"
            )
        by_tool.setdefault(key, []).append(rule)

    permission: dict[str, object] = {}
    for key, tool_rules in by_tool.items():
        ordered = sorted(tool_rules, key=lambda rule: _ACTION_ORDER[rule.action])
        if len(ordered) == 1 and ordered[0].pattern is None:
            permission[key] = ordered[0].action
        else:
            permission[key] = {(rule.pattern or "*"): rule.action for rule in ordered}
    return permission


class OpenCodeAdapter(PlatformAdapter):
    """Render bun-off artifacts to OpenCode's native workspace layout."""

    name: ClassVar[str] = "opencode"
    layout: ClassVar[PlatformLayout] = OPENCODE_LAYOUT

    @renders(Rule)
    def _rule(self, artifact: Rule, *, platform: str, scope: Scope) -> list[Operation]:
        """Write a rule to ``.opencode/rules/`` and register the rules glob in ``opencode.json``."""
        del platform
        if artifact.globs:
            _log.warning(
                "rule %r has globs but OpenCode loads instructions globally; "
                "scope will not be enforced (deploying unscoped)",
                artifact.name,
            )
        root = require_workspace_root(scope)
        parts = [self.layout.config_root, "rules"]
        if artifact.category:
            parts.append(artifact.category)
        parts.append(f"{artifact.name}.md")
        file_target = root.joinpath(*parts)
        return [
            FileOperation(
                target=file_target,
                content=artifact.content,
                merge=MergeStrategy.OVERWRITE,
                description=f"opencode rule {artifact.name}",
            ),
            opencode_instructions_glob_op(root),
        ]

    @renders(Permissions)
    def _permissions(
        self, artifact: Permissions, *, platform: str, scope: Scope
    ) -> list[Operation]:
        """Merge permission rules into ``opencode.json`` under ``permission``."""
        del platform
        root = require_workspace_root(scope)
        permission = _opencode_permission_block(artifact.rules_for("opencode"))
        return [
            FileOperation(
                target=self.layout.settings_path(root),
                content=dumps_json({"permission": permission}),
                merge=MergeStrategy.MERGE,
                description="opencode permissions",
            )
        ]

    @renders(EventHooks)
    def _event_hooks(self, artifact: EventHooks, *, platform: str, scope: Scope) -> list[Operation]:
        """Write per-hook scripts and the auto-loaded ``boff-hooks.js`` plugin for OpenCode."""
        del platform
        hooks = artifact.hooks_for("opencode")
        if not hooks:
            return []
        root = require_workspace_root(scope)
        ops: list[Operation] = list(self._hook_script_ops(hooks, root))
        ops.append(
            FileOperation(
                target=root / self.layout.config_root / "plugins" / "boff-hooks.js",
                content=_opencode_plugin(hooks),
                merge=MergeStrategy.OVERWRITE,
                description="opencode event-hook plugin",
            )
        )
        return ops

    @renders(OutputStyle, drops=True)
    def _output_style(
        self, artifact: OutputStyle, *, platform: str, scope: Scope
    ) -> list[Operation]:
        """Warn and skip: OpenCode has no output-style surface.

        Its nearest analogue is a primary agent, but an agent's ``prompt`` *replaces* the base
        system prompt rather than appending to it, so ``keep-coding-instructions: true`` has no
        encoding. boff does not translate: authors write the OpenCode side explicitly as an
        ``agents:`` entry with ``mode: primary``, selected via ``settings.opencode.default_agent``.
        """
        del platform, scope
        _log.warning(
            "output style %r has no OpenCode equivalent; skipping (scope it with "
            "available_on: [claude], and add an agents: entry with mode: primary for OpenCode)",
            artifact.name,
        )
        return []

    @renders(Agent)
    def _agent(self, artifact: Agent, *, platform: str, scope: Scope) -> list[Operation]:
        """Write a subagent to ``.opencode/agents/<name>.md`` with frontmatter."""
        del platform
        root = require_workspace_root(scope)
        frontmatter: dict[str, object] = {"description": artifact.description}
        if artifact.mode is not None:
            frontmatter["mode"] = artifact.mode
        model = artifact.model_for("opencode")
        if model is not None:
            frontmatter["model"] = model
        permission = _opencode_permission_block(artifact.permissions_for("opencode"))
        if permission:
            frontmatter["permission"] = permission
        return [
            FileOperation(
                target=root / self.layout.config_root / "agents" / f"{artifact.name}.md",
                content=frontmatter_block(frontmatter) + artifact.content,
                merge=MergeStrategy.OVERWRITE,
                description=f"opencode agent {artifact.name}",
            )
        ]
