"""Deterministic, no-LLM handoff digest.

Providers extract structured facts from their native transcript format into
:class:`DigestFacts`; :func:`render_digest` formats them into the markdown block
that seeds a target platform during migration.
"""

from __future__ import annotations

from dataclasses import dataclass, field

_MAX_GOAL_LEN = 280


@dataclass
class DigestFacts:
    """Structured facts pulled mechanically from a conversation transcript."""

    project_path: str = ""
    branch: str | None = None
    user_goals: list[str] = field(default_factory=list[str])
    plans: list[str] = field(default_factory=list[str])
    edited_files: list[str] = field(default_factory=list[str])
    todos: list[str] = field(default_factory=list[str])


def truncate(text: str, limit: int = _MAX_GOAL_LEN) -> str:
    """Collapse whitespace and clip ``text`` to ``limit`` characters."""
    flat = " ".join(text.split())
    if len(flat) <= limit:
        return flat
    return flat[: limit - 1].rstrip() + "…"


def _bullets(items: list[str]) -> list[str]:
    """Format a list of strings as markdown bullet points."""
    return [f"- {item}" for item in items] or ["- (none captured)"]


def render_digest(facts: DigestFacts) -> str:
    """Render :class:`DigestFacts` as a markdown handoff block."""
    lines: list[str] = ["# Migrated context handoff", ""]
    lines.append(
        "This file was generated by bun-off when migrating context between coding "
        "assistants. It summarizes the prior session so work can continue."
    )
    lines.append("")
    lines.append(f"- Project: `{facts.project_path}`")
    if facts.branch:
        lines.append(f"- Branch: `{facts.branch}`")
    lines.append("")

    lines.append("## Recent goals")
    lines.extend(_bullets([truncate(goal) for goal in facts.user_goals]))
    lines.append("")

    lines.append("## Plans carried over")
    lines.extend(_bullets(facts.plans))
    lines.append("")

    lines.append("## Recently edited files")
    lines.extend(_bullets(facts.edited_files))
    lines.append("")

    lines.append("## Open todos")
    lines.extend(_bullets(facts.todos))
    lines.append("")

    return "\n".join(lines)
